from General.auxiliar import total_variation_distance

def calculate_fitness_value_standard(d: dict, w: list) -> int:
    """
    Calculate the fitness value of an individual based on its performance variables
    
    INPUT
        d: dictionary
            dictionary with performance variables
        w: list
            list of weights of size 5 (0 or 1)

    OUTPUT
        integer
            Return the fitness value of an individual
    """ 

    return d['Player wins']*w[0] + \
           d['Coach wins']*w[1] + \
           d['Player outside moves']*w[2] + \
           d['Player overlapped moves']*w[3] + \
           d['Draws']*w[4]    


def calculate_fitness_value_diversity(d: dict, w: list) -> int:
    """
    Calculate the fitness value of an individual based on its diversity

    INPUT:
        d: dictionary
            dictionary with the frequency of all the moves generated by the individual
        w: list
            list of weights of size 5 (0 or 1)

    OUTPUT:
        integer
            Return the fitness value of an individual
    """

    return d['Player wins']*w[0] + \
           d['Coach wins']*w[1] + \
           d['Player outside moves']*w[2] + \
           d['Player overlapped moves']*w[3] + \
           d['Draws']*w[4] - \
            total_variation_distance(d)
    